spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 5s
    gateway:
      routes:
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 6
                key-resolver: "#{@ipKeyResolver}"

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}}
    prefer-ip-address: true
    ip-address: 127.0.0.1

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/