server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}}
    prefer-ip-address: true
    ip-address: 127.0.0.1
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

feign:
  client:
    config:
      productClient:
        connectTimeout: 2000
        readTimeout: 3000


management.endpoint.health.show-details: always