server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:products;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}}
    prefer-ip-address: true
    ip-address: 127.0.0.1
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/